# Generated by Django 3.1.3 on 2020-11-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20201120_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
