# Generated by Django 3.1.3 on 2020-11-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20201120_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
