# Generated by Django 3.1.3 on 2020-11-20 21:45

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_year',
            field=models.IntegerField(default=1966, validators=[main_app.validators.year_validator]),
            preserve_default=False,
        ),
    ]
