# Generated by Django 3.1.3 on 2020-11-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_userprofile_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/images/user.png', upload_to='profiles'),
        ),
    ]
