# Generated by Django 3.1.3 on 2020-11-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_auto_20201121_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/images/users.jpg', upload_to='profiles'),
        ),
    ]
