# Generated by Django 3.1.3 on 2020-11-09 17:41

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201109_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='build_year',
            field=models.IntegerField(validators=[main_app.validators.year_validator]),
        ),
    ]
