# Generated by Django 3.1.3 on 2020-11-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201109_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='test',
        ),
    ]
