# Generated by Django 3.1.3 on 2020-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201111_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_type',
            field=models.CharField(choices=[('web_image', 'WEB Image'), ('local_image', 'Local Image'), ('no_image', 'No Image')], default='-', max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
