# Generated by Django 3.1.3 on 2020-11-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201112_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, default='https://dox.abv.bg/download?id=daa57ce6c1#'),
        ),
    ]
