# Generated by Django 3.1.3 on 2020-11-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201112_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, default='https://www.google.bg/search?hl=en-BG&tbs=simg:CAQSvQIJkhAwTjtkzRQasQILELCMpwgaYgpgCAMSKPEGwAO9AeEB4gHOEs8SnxLGA7oCriafNLsouz_11PZs9uT_1APfY9oDQaMIfoNCuAlBS16nLNCZSLvjilqyZ5lUJPCjeE1YaDjQTwSBRQreBi-ed8VDVVasKkCiAEDAsQjq7-CBoKCggIARIE3RBchQwLEJ3twQkaqQEKJAoQYXV0b21vdGl2ZSBkZWNhbNqliPYDDAoKL20vMGg4bHA3aAokChBhdXRvbW90aXZlIHBhaW502qWI9gMMCgovbS8waDhtd2xoChgKBGF1ZGnapYj2AwwKCi9tLzBoNXoyMGMKHwoMY2FyIGV4dGVyaW9y2qWI9gMLCgkvai9nNmZtYm0KIAoMZWxlY3RyaWMgY2Fy2qWI9gMMCgovbS8wM25sZjJ3DA&q=audi&tbm=isch&sa=X&ved=2ahUKEwjS7JbA7f3sAhWNxIsKHd1oDrwQwg4oAHoECBAQNg'),
        ),
    ]
