# Generated by Django 3.1.3 on 2020-11-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20201114_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_file',
            field=models.ImageField(blank=True, default='/images/car.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, default='https://s.clipartkey.com/mpngs/s/39-392476_transparent-jeep-clipart-audi-a4-2014-front.png', null=True),
        ),
    ]
